# Generated by Django 5.2.12 on 2026-09-14 04:26

import dashboard.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('configuration_snapshot', models.JSONField(default=dict)),
                ('module_values_h', models.JSONField(default=dict)),
                ('module_breakdowns', models.JSONField(default=dict)),
                ('automatic_value_h', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('adjustment_h', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('adjustment_mxn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('adjustment_justification', models.TextField(blank=True)),
                ('final_value_h', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('progress', 'En progreso'), ('complete', 'Completo'), ('pending', 'Con pendientes')], default='progress', max_length=12)),
                ('pending_reasons', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('hour_value_mxn', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=12)),
                ('calorie_goal', models.PositiveIntegerField(default=2200)),
                ('protein_goal_g', models.PositiveIntegerField(default=160)),
                ('fat_priority', models.CharField(choices=[('maintain', 'Mantener'), ('lose', 'Bajar'), ('urgent', 'Bajar urgente')], default='urgent', max_length=16)),
                ('muscle_priority', models.CharField(choices=[('maintain', 'Mantener'), ('gain', 'Subir'), ('urgent', 'Subir urgente')], default='gain', max_length=16)),
                ('social_priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('priority', 'Prioritaria')], default='priority', max_length=16)),
                ('pricing_versions', models.JSONField(default=dashboard.models.default_pricing_versions)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('biological_sex', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('unspecified', 'Sin especificar')], default='unspecified', max_length=12)),
            ],
            options={
                'verbose_name': 'configuracion global',
                'verbose_name_plural': 'configuraciones globales',
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BodyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_am_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_pm_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('abdomen_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('visual_fat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muscularity_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('face_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('body_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('llm_description', models.TextField(blank=True)),
                ('analysis_json', models.JSONField(default=dict)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='dashboard.dayrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_type', models.CharField(max_length=60)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('action', models.CharField(default='update', max_length=20)),
                ('previous_data', models.JSONField(default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dashboard.dayrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('steps', 'Pasos intencionales'), ('pushups', 'Lagartijas'), ('functional_moderate', 'Funcional moderado'), ('functional_intense', 'Funcional intenso'), ('gym', 'Gimnasio')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(editable=False, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('coefficient_version', models.CharField(default='energy-1.0', max_length=24)),
                ('estimated_active_kcal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.dayrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eaten_at', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='meals/%Y/%m/%d/')),
                ('foods', models.JSONField(default=list)),
                ('calories', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('alcoholic_drink', models.CharField(blank=True, max_length=120)),
                ('beverage_volume_ml', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('alcohol_abv_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('pure_alcohol_ml', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('corrected_manually', models.BooleanField(default=False)),
                ('ai_result', models.JSONField(default=dict)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='dashboard.dayrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passive_positive_minutes', models.PositiveIntegerField(default=0)),
                ('passive_positive_description', models.TextField(blank=True)),
                ('passive_intermediate_minutes', models.PositiveIntegerField(default=0)),
                ('passive_intermediate_description', models.TextField(blank=True)),
                ('passive_negative_minutes', models.PositiveIntegerField(default=0)),
                ('passive_negative_description', models.TextField(blank=True)),
                ('active_intermediate_minutes', models.PositiveIntegerField(default=0)),
                ('active_intermediate_description', models.TextField(blank=True)),
                ('active_positive_minutes', models.PositiveIntegerField(default=0)),
                ('active_positive_description', models.TextField(blank=True)),
                ('broken_glasses', models.PositiveIntegerField(default=0)),
                ('elo', models.IntegerField(blank=True, null=True)),
                ('solved_problems', models.PositiveIntegerField(default=0)),
                ('soa_exercises', models.PositiveIntegerField(default=0)),
                ('personal_commits', models.PositiveIntegerField(default=0)),
                ('prior_streak', models.PositiveIntegerField(default=0)),
                ('resulting_streak', models.PositiveIntegerField(default=0)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mental', to='dashboard.dayrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fell_asleep_at', models.DateTimeField(blank=True, null=True)),
                ('woke_up_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment_minutes', models.IntegerField(default=0)),
                ('rising_category', models.CharField(choices=[('quick', '0-1 min'), ('medium', '1-15 min'), ('slow', 'Mas de 15 min'), ('na', 'No aplica / no dormi')], default='quick', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('no_sleep', models.BooleanField(default=False)),
                ('total_sleep_minutes', models.IntegerField(default=0)),
                ('midpoint_minute', models.IntegerField(blank=True, null=True)),
                ('circadian_reference_minute', models.IntegerField(blank=True, null=True)),
                ('circadian_deviation_minutes', models.IntegerField(blank=True, null=True)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sleep', to='dashboard.dayrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_minutes', models.PositiveIntegerField(default=0)),
                ('friends_minutes', models.PositiveIntegerField(default=0)),
                ('mixed_friends_minutes', models.PositiveIntegerField(default=0)),
                ('mixed_target_minutes', models.PositiveIntegerField(default=0)),
                ('target_friends_minutes', models.PositiveIntegerField(default=0)),
                ('journal', models.TextField(blank=True)),
                ('rewarded_minutes', models.JSONField(default=dict)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='dashboard.dayrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('body', 'Progreso corporal'), ('nutrition', 'Nutricion'), ('activity', 'Actividad fisica'), ('sleep', 'Sueno'), ('mental', 'Mental y digital'), ('social', 'Vida social')], max_length=16)),
                ('source_text', models.TextField(blank=True)),
                ('source_file', models.FileField(blank=True, upload_to='sources/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('correction', 'Requiere correccion'), ('error', 'Error')], default='draft', max_length=16)),
                ('prompt_version', models.CharField(default='1.0', max_length=32)),
                ('model_used', models.CharField(blank=True, max_length=160)),
                ('result_json', models.JSONField(default=dict)),
                ('correction_json', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_submissions', to='dashboard.dayrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BodyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('body_front', 'Cuerpo frontal'), ('body_side', 'Cuerpo lateral'), ('body_back', 'Cuerpo posterior'), ('face_front', 'Rostro frontal'), ('face_side', 'Rostro lateral')], max_length=20)),
                ('image', models.ImageField(upload_to='body/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dashboard.bodyentry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('body', 'kind'), name='unique_body_photo_kind')],
            },
        ),
        migrations.CreateModel(
            name='SectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('body', 'Progreso corporal'), ('nutrition', 'Nutricion'), ('activity', 'Actividad fisica'), ('sleep', 'Sueno'), ('mental', 'Mental y digital'), ('social', 'Vida social')], max_length=16)),
                ('captured', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('idle', 'Sin proceso'), ('processing', 'Procesando'), ('done', 'Procesado'), ('correction', 'Requiere correccion'), ('error', 'Error')], default='idle', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_states', to='dashboard.dayrecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day', 'module'), name='unique_day_module_state')],
            },
        ),
    ]
