# Generated by Django 5.2.12 on 2026-09-14 04:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taken_at', models.TimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('dose', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('unit', models.CharField(default='mg', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='dashboard.dayrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
