# Generated by Django 5.2.12 on 2026-09-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_supplement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyphoto',
            name='image',
        ),
        migrations.AddField(
            model_name='bodyphoto',
            name='image_file_id',
            field=models.CharField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='bodyphoto',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
