# Generated by Django 5.2.12 on 2026-09-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_bodyphoto_image_bodyphoto_image_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayrecord',
            name='nutrition_notes',
            field=models.TextField(blank=True),
        ),
    ]
