# Generated by Django 5.2.12 on 2026-09-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dayrecord_nutrition_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionstate',
            name='module',
            field=models.CharField(choices=[('body', 'Progreso corporal'), ('nutrition', 'Nutricion'), ('activity', 'Actividad fisica'), ('sleep', 'Sueño'), ('mental', 'Mental y digital'), ('social', 'Vida social')], max_length=16),
        ),
        migrations.AlterField(
            model_name='sourcesubmission',
            name='module',
            field=models.CharField(choices=[('body', 'Progreso corporal'), ('nutrition', 'Nutricion'), ('activity', 'Actividad fisica'), ('sleep', 'Sueño'), ('mental', 'Mental y digital'), ('social', 'Vida social')], max_length=16),
        ),
    ]
