# Generated by Django 5.2.12 on 2026-09-14 05:25

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_sectionstate_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='challenge_start_date',
            field=models.DateField(default=dashboard.models.default_challenge_start_date),
        ),
    ]
